MOVIE PROJECT/movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MOVIE PROJECT/movie_project/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('addmovie',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

MOVIE PROJECT/movie_project/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=25)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

MOVIE PROJECT/movie_project/movieapp/forms.py
from django import forms
from .models import Movie

class FormMovie(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

MOVIE PROJECT/movie_project/movieapp/views.py
from django.shortcuts import render, redirect

from .forms import FormMovie
from .models import Movie


# Create your views here.

def index(request):
    movie_list = Movie.objects.all()
    context={
        'movies':movie_list
    }
    return render(request, 'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)

    return render(request,'detail.html',{'movie_detail':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('description')
        year = request.POST.get('year')
        img = request.FILES['img']
        new_movie=Movie(name=name,desc=desc,year=year,img=img)
        new_movie.save()
        return redirect('/')
    return render(request,'addmovie.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=FormMovie(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

MOVIE PROJECT/movie_project/templates/addmovie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add movie</title>
</head>
<body>
<form action="addmovie" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="description" placeholder="enter movie description"><br>
    <input type="number" name="year" placeholder="enter release year"><br>
    <input type="file" name='img'> <br>
    <input type="submit" >

</form>
</body>
</html>

MOVIE PROJECT/movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-info ">
  <a class="navbar-brand" href="#">
<!--    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    <h3>Movie Point</h3>
  </a>
</nav>
{% block body%}

{% endblock %}
</body>
</html>

MOVIE PROJECT/movie_project/templates/delete.html
{% extends 'base.html '%}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="container " >
    <h2>Are you sure you want to delete this movie ?</h2>
    <input type="submit" class="bg-primary">
    </div>
</form>
{% endblock %}

MOVIE PROJECT/movie_project/templates/detail.html
{% extends 'base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col md-6">
            <img class="card-img-top" src="{{movie_detail.img.url}}" alt="Card image cap">
        </div>
                <div class="card" style="width: 750px ">

                  <div class="card-body">
                    <h5 class="card-title">{{movie_detail.name}}</h5>
                    <p class="card-text">{{movie_detail.desc}}</p>
                      <a href="{% url 'movieapp:update' movie_detail.id %}" class="card-link">Update</a>
                      <a href="{% url 'movieapp:delete' movie_detail.id %}" class="card-link">Delete</a>

                  </div>
                </div>

    </div>
</div>

{% endblock %}

MOVIE PROJECT/movie_project/templates/index.html
{% extends 'base.html' %}
{% block body%}
<button class="btn-btn-primary m-1 p-1"><a href="addmovie">ADD MOVIES</a></button>
<div class="container">
    <div class="row">
    {% for i in movies %}
        <div class="col-md-3 mt-4">
            <div class="card " >
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.year}}</p>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View More</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>


<!--{% for i in movies %}-->
<!--<img src="{{i.img.url}}" width="150" height="150">-->
<!--<a href="{% url 'movieapp:detail' i.id %}"> <h4>{{i.name}}</h4> </a><br>-->
<!--{% endfor %}-->
{% endblock %}

MOVIE PROJECT/movie_project/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock %}